<!DOCTYPE html>
<html lang="en">

	<head>
		<meta charset="utf-8" />
		<title>Ben Silver Magic</title>
		<meta name="keywords" content="'Ben Silver', Magic, Magician, Street Magic, Illusionist, Mentalism, Performer, Entertainer, Magic, Tricks, ' San Diego Magicians'" />
		<meta name="description" content="Ben Silver is one of the premier magicians in California. Ben Silver's dry humor, quick wit and nonchalant style of magic have made him a crowd favorite. No red nose, cheesy dialog, or over indulgent delivery, just in your face, hard-hitting illusions that will leave you scratching your head and asking for more." />
  		<link rel="shortcut icon" href="/images/favicon.ico" type="image/x-icon" />
  		<link rel="stylesheet" href="css/bensilvermagic.css" type="text/css">
  		<link rel="stylesheet" href="css/ringbearerFont.css" type="text/css">
  		
  		<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.6.4/jquery.min.js"></script>
  		<script type="text/javascript" src="/js/bensilvermagic.js"></script>
  		  		
  		<!--[if lte IE 8]>
			<script src="/js/html5.js" type="text/javascript"></script>
		<![endif]-->
		
		<!--[if IE]>
			<link rel="stylesheet" href="css/ie.css" type="text/css">
		<![endif]-->
	</head>

	<body>
		<?php include("navbar.php"); ?>
		
		<?php include("header.php"); ?>
		
		<section id="content">
	