<!DOCTYPE html>
<html lang="en">

	<head>
		<meta charset="utf-8" />
		<title>Ben Silver Magic</title>
  		<link rel="shortcut icon" href="/images/favicon.ico" type="image/x-icon" />
  		<link rel="stylesheet" href="css/bensilvermagic.css" type="text/css">
  		<link rel="stylesheet" href="css/ringbearerFont.css" type="text/css">
  		<link rel="stylesheet" href="css/darkwoodLayout.css" type="text/css">
  		
  		<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.6.4/jquery.min.js"></script>
  		<script type="text/javascript" src="/js/bensilvermagic.js"></script>
  		  		
  		<!--[if lte IE 8]>
  			<link rel="stylesheet" href="css/ie7.css" type="text/css">
			<script src="/js/html5.js" type="text/javascript"></script>
		<![endif]-->
		
		<!--[if IE]>
			<link rel="stylesheet" href="css/ie.css" type="text/css">
		<![endif]-->
	</head>

	<body>
		<?php include("navbar.php"); ?>
		
		<div id="wrapper">
			<?php include("header.php"); ?>
			
			<section id="content">